export const SKILLS = [
    'Git',
    'Javascript',
    'Angular',
    'VueJS',
    'React',
    'Redux',
    'Jest',
    'styled-components',
    'Sass',
    'Bootstrap',
    'Material-UI',
    'HTML5',
    'Semantic HTML',
    'Java',
    'Spring Framework',
    'Mongoose',
    'Mongo',
    'mySQL',
    'Domain Driven Design',
    'Single Page Applications',
    'Agile Development',
];
