export const SKILLS = [
    'Git',
    'Javascript',
    'Angular',
    'VueJS',
    'React',
    'Redux',
    'Testing Library',
    'Enzyme',
    'Jest',
    'styled-components',
    'Sass',
    'Bootstrap',
    'Material-UI',
    'Vuetify',
    'HTML5',
    'Semantic HTML',
    'Java',
    'Spring',
    'Mongoose',
    'MongoDB',
    'SQL',
    'mySQL',
    'Flutter',
    'Dart',
    'Domain Driven Design',
    'Single Page Applications',
    'Front-End Architecture',
    'Progressive Web Apps',
    'Agile Development',
    'Knowledge Sharing',
];
